#!/bin/bash
user=$1
Quota=${2:-0}
iplimit=${3:-0}
bug=$4
uuid=$(cat /proc/sys/kernel/random/uuid)
exp=$(date -d "+30 minutes" +"%Y-%m-%d %H:%M:%S")

source /var/lib/kyt/ipvps.conf
if [[ "$IP" == "" ]]; then
    domain=$(cat /etc/xray/domain)
else
    domain=$IP
fi

sed -i '/#trojan$/a\### '"$user $exp"'\
},{"password": "'$uuid'","email": "'$user'"' /etc/xray/config.json

if [[ $iplimit -gt 0 ]]; then
    mkdir -p /etc/kyt/limit/trojan/ip
    echo "$iplimit" > /etc/kyt/limit/trojan/ip/$user
fi

c=$(echo "$Quota" | sed 's/[^0-9]*//g')
d=$(( c * 1024 * 1024 * 1024 ))
if [[ $c != "0" ]]; then
  echo "$d" >/etc/trojan/$user
fi

DATADB=$(grep "^###" /etc/trojan/.trojan.db | grep -w "$user" | awk '{print $2}')
if [[ "$DATADB" != "" ]]; then
  sed -i "/\b$user\b/d" /etc/trojan/.trojan.db
fi
echo "### $user $exp $uuid $Quota $iplimit" >> /etc/trojan/.trojan.db

# Generate Trojan links
trojanlink="trojan://$uuid@$bug:443?security=tls&host=$domain&type=ws&sni=$domain#$user"

systemctl restart xray > /dev/null 2>&1
systemctl restart nginx > /dev/null 2>&1
service cron restart > /dev/null 2>&1

echo "SUCCESS"
echo "Remarks: $user"
echo "Domain: $domain"
echo "User Quota: $Quota GB"
echo "User IP Limit: $iplimit IP"
echo "Password: $uuid"
echo "Expired: $exp"
echo "Link Trojan: $trojanlink"