#!/bin/bash
user=$1
Quota=${2:-0}
iplimit=${3:-0}
bug=$4
uuid=$(cat /proc/sys/kernel/random/uuid)
exp=$(date -d "+30 minutes" +"%Y-%m-%d %H:%M:%S")

source /var/lib/kyt/ipvps.conf
if [[ "$IP" == "" ]]; then
    domain=$(cat /etc/xray/domain)
else
    domain=$IP
fi

sed -i '/#vless$/a\### '"$user $exp"'\
},{"id": "'$uuid'","email": "'$user'"' /etc/xray/config.json
sed -i '/#vlessgrpc$/a\## '"$user $exp"'\
},{"id": "'$uuid'","email": "'$user'"' /etc/xray/config.json

if [[ $iplimit -gt 0 ]]; then
    mkdir -p /etc/kyt/limit/vless/ip
    echo "$iplimit" > /etc/kyt/limit/vless/ip/$user
fi

c=$(echo "$Quota" | sed 's/[^0-9]*//g')
d=$(( c * 1024 * 1024 * 1024 ))
if [[ $c != "0" ]]; then
  echo "$d" >/etc/vless/$user
fi

DATADB=$(grep "^###" /etc/vless/.vless.db | grep -w "$user" | awk '{print $2}')
if [[ "$DATADB" != "" ]]; then
  sed -i "/\b$user\b/d" /etc/vless/.vless.db
fi
echo "### $user $exp $uuid $Quota $iplimit" >> /etc/vless/.vless.db

# Generate VLESS links (ws TLS, ws none TLS, grpc TLS)
asu=$(cat <<EOF
{
  "v":"2",
  "ps":"$user",
  "add":"$bug",
  "port":"443",
  "id":"$uuid",
  "flow":"",
  "net":"ws",
  "path":"/vless",
  "type":"none",
  "host":"$domain",
  "tls":"tls"
}
EOF
)
vlesslink1="vless://$(echo $asu | base64 -w 0)"

ask=$(cat <<EOF
{
  "v":"2",
  "ps":"$user",
  "add":"$bug",
  "port":"80",
  "id":"$uuid",
  "flow":"",
  "net":"ws",
  "path":"/vless",
  "type":"none",
  "host":"$domain",
  "tls":"none"
}
EOF
)
vlesslink2="vless://$(echo $ask | base64 -w 0)"

grpc=$(cat <<EOF
{
  "v":"2",
  "ps":"$user",
  "add":"$bug",
  "port":"443",
  "id":"$uuid",
  "flow":"",
  "net":"grpc",
  "path":"vless-grpc",
  "type":"none",
  "host":"$domain",
  "tls":"tls"
}
EOF
)
vlesslink3="vless://$(echo $grpc | base64 -w 0)"

systemctl restart xray > /dev/null 2>&1
systemctl restart nginx > /dev/null 2>&1
service cron restart > /dev/null 2>&1

echo "SUCCESS"
echo "Remarks: $user"
echo "Domain: $domain"
echo "User Quota: $Quota GB"
echo "User IP Limit: $iplimit IP"
echo "UUID: $uuid"
echo "Expired: $exp"
echo "Link TLS: $vlesslink1"
echo "Link none TLS: $vlesslink2"
echo "Link GRPC: $vlesslink3"