#!/bin/bash
# Hapus user Trojan berdasarkan username

config_file="/etc/xray/config.json"
service_name="xray"

echo -e "====================="
echo -e "❌ HAPUS USER TROJAN"
echo -e "====================="
read -p "👥 Masukkan username " user

if ! grep -q "^### $user " "$config_file"; then
    echo "❌ User $user tidak ditemukan!"
    exit 1
fi

sed -i "/^### $user /,/^},{/d" "$config_file"

systemctl restart $service_name
echo -e "✅ User $user berhasil dihapus!"