#!/bin/bash
config_file="/etc/xray/config.json"

echo "====================="
echo "❌ HAPUS USER VMESS"
echo "====================="
read -p "Masukkan Username: " user

# Cari user berdasarkan ### atau email
if grep -qw "$user" "$config_file"; then
    # Hapus tanda komentar
    sed -i "/^### $user /d" "$config_file"
    # Hapus block email user
    sed -i "/\"email\": \"$user\"/d" "$config_file"
    echo "✅ User $user berhasil dihapus dari VMESS!"
    systemctl restart xray
else
    echo "❌ User $user tidak ditemukan!"
fi