#!/bin/bash

echo "====================="
echo "❌ HAPUS USER SSH"
echo "====================="
read -p "Masukkan Username: " user

if id "$user" &>/dev/null; then
    userdel -r "$user" &>/dev/null
    echo "✅ User $user berhasil dihapus dari SSH!"
else
    echo "❌ User $user tidak ditemukan!"
fi