#!/bin/bash
user=$1

if [[ -z $user ]]; then
    echo "❌ Masukkan username!"
    exit 1
fi

if getent passwd $user > /dev/null 2>&1; then
    pkill -u $user
    userdel -r $user
    echo "✅ User SSH $user berhasil dihapus!"
else
    echo "❌ User SSH $user tidak ditemukan!"
fi