#!/bin/bash
config_file="/etc/xray/config.json"

echo "====================="
echo "❌ HAPUS USER TROJAN"
echo "====================="
read -p "Masukkan Username: " user

if grep -qw "$user" "$config_file"; then
    sed -i "/^### $user /d" "$config_file"
    sed -i "/\"password\": \"$user\"/d" "$config_file"
    echo "✅ User $user berhasil dihapus dari TROJAN!"
    systemctl restart xray
else
    echo "❌ User $user tidak ditemukan!"
fi