#!/bin/bash
config_file="/etc/xray/config.json"
user=$1

if [[ -z $user ]]; then
    echo "❌ Masukkan username!"
    exit 1
fi

if grep -qw "$user" "$config_file"; then
    # hapus user dari config
    sed -i "/^### $user /,/^},{/d" $config_file
    systemctl restart xray
    echo "✅ User $user berhasil dihapus!"
else
    echo "❌ User $user tidak ditemukan!"
fi